#!/usr/bin/env bash
#################################################
# Name:         factorial
# Author:       
# 
# Description:  This function calculates factorials
#
# Dependencies: 
#
# Usage:        $ factorial 10
#
factorial () {
	local num=$1
	if ((num==1)); then
		echo '1'
		return
	fi
	local n1=$((num-1))
	local f=$(factorial "$n1")
	local res=$((f*num))
	echo "$res"
}