#! /usr/bin/env bash -
#################################################
# Name:         smash
# Author:       Jesse_b
# 
# Description:  This function will perform a pgrep on the argument string and kill all PIDs associated with it.
#
# Dependencies: 
#   -> yorn.ask function
#
# Usage:        $ smash [SEARCH_STRING]
#
smash () {
	local T_PROC="$1"
	local T_PIDS=($(pgrep -i "$T_PROC"))
	if [[ "${#T_PIDS[@]}" -ge 1 ]]; then
		echo "Found the following processes:"
		for pid in "${T_PIDS[@]}"; do
			echo "$pid" "$(ps -p "$pid" -o comm= | awk -F'/' '{print $NF}')" | column -t
		done
		if ( yorn.ask "Kill them?" ); then
			for pid in "${T_PIDS[@]}"; do
				echo "Killing ${pid}..."
				( kill -15 "$pid" ) && continue
				sleep 2
				( kill -2 "$pid" ) && continue
				sleep 2
				( kill -1 "$pid" ) && continue
				echo "What the hell is this thing?" >&2 && return 1
			done
		else
			echo "Exiting..."
			return 0
		fi
	else
		echo "No processes found for: $1" >&2 && return 1
	fi
}